//Povray v3 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Update (2010): Noel O'Boyle and Steven Wathen
//Date: Tue Jan 13 11:25:42 UTC 2026

//Set some global parameters for display options
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"

// create a regular point light source
light_source {
  <3.83546,3.1219,-7.78467>
  color rgb <1,1,1>    // light's color
}

// set a color of the background (sky)
background { color rgb <0.95 0.95 0.95> }

// perspective (default) camera
camera {
  location  <1.83546,0.1219,-9.78467>
  look_at   <1.83546,0.1219,0.215327>
  right     x*image_width/image_height
}

//Include header for povray
#include "babel_povray3.inc"

//Use PovRay3.6
#version 3.6;

//Print name of molecule while rendering
#render "\b\b \n\n"

//Coodinates of atoms 1 - 9
#declare mol_0_pos_1 = <0.96753,-0.0738043,0.0526897>;
#declare mol_0_pos_2 = <2.48182,-0.0673766,0.0560259>;
#declare mol_0_pos_3 = <2.9635,0.592243,1.21748>;
#declare mol_0_pos_4 = <0.58273,-0.588182,-0.832272>;
#declare mol_0_pos_5 = <0.57553,0.948499,0.0642613>;
#declare mol_0_pos_6 = <0.58205,-0.573076,0.947766>;
#declare mol_0_pos_7 = <2.87324,0.446091,-0.827546>;
#declare mol_0_pos_8 = <2.86881,-1.09052,0.0599445>;
#declare mol_0_pos_9 = <2.62392,1.50322,1.1996>;

//Povray-description of atoms 1 - 9
#declare mol_0_atom1 = object {
	  Atom_C
	  translate mol_0_pos_1
	 }
#declare mol_0_atom2 = object {
	  Atom_C
	  translate mol_0_pos_2
	 }
#declare mol_0_atom3 = object {
	  Atom_O
	  translate mol_0_pos_3
	 }
#declare mol_0_atom4 = object {
	  Atom_H
	  translate mol_0_pos_4
	 }
#declare mol_0_atom5 = object {
	  Atom_H
	  translate mol_0_pos_5
	 }
#declare mol_0_atom6 = object {
	  Atom_H
	  translate mol_0_pos_6
	 }
#declare mol_0_atom7 = object {
	  Atom_H
	  translate mol_0_pos_7
	 }
#declare mol_0_atom8 = object {
	  Atom_H
	  translate mol_0_pos_8
	 }
#declare mol_0_atom9 = object {
	  Atom_H
	  translate mol_0_pos_9
	 }

//Povray-description of bonds 1 - 8
#if (BAS)
#declare mol_0_bond0 = object {
	  bond_1
	  scale <1.51431,1.0000,1.0000>
	  rotate <0.0000,0.0000,0.243202>
	  rotate <0.0000,-0.126233,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond1 = object {
	  bond_1
	  scale <1.41989,1.0000,1.0000>
	  rotate <0.0000,0.0000,27.6816>
	  rotate <0.0000,-67.475,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond2 = object {
	  bond_1
	  scale <1.09353,1.0000,1.0000>
	  rotate <0.0000,0.0000,-28.0591>
	  rotate <0.0000,113.5,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond3 = object {
	  bond_1
	  scale <1.09494,1.0000,1.0000>
	  rotate <0.0000,0.0000,69.0125>
	  rotate <0.0000,-178.309,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond4 = object {
	  bond_1
	  scale <1.095,1.0000,1.0000>
	  rotate <0.0000,0.0000,-27.1264>
	  rotate <0.0000,-113.3,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond5 = object {
	  bond_1
	  scale <1.09433,1.0000,1.0000>
	  rotate <0.0000,0.0000,27.9828>
	  rotate <0.0000,66.1067,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond6 = object {
	  bond_1
	  scale <1.09389,1.0000,1.0000>
	  rotate <0.0000,0.0000,-69.2806>
	  rotate <0.0000,-0.580145,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond7 = object {
	  bond_1
	  scale <0.972376,1.0000,1.0000>
	  rotate <0.0000,0.0000,69.5304>
	  rotate <0.0000,176.986,0.0000>
	  translate mol_0_pos_3
	 }
#end //(BAS-Bonds)

#if (CST)
#declare mol_0_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.757153,1.0000,1.0000>
	    rotate <0.0000,0.0000,0.243202>
	    rotate <0.0000,-0.126233,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.757153,1.0000,1.0000>
	    rotate <0.0000,0.0000,180.243>
	    rotate <0.0000,-0.126233,0.0000>
	    translate mol_0_pos_2
	   }
	  }
	 }

#declare mol_0_bond1 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.709945,1.0000,1.0000>
	    rotate <0.0000,0.0000,27.6816>
	    rotate <0.0000,-67.475,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.709945,1.0000,1.0000>
	    rotate <0.0000,0.0000,207.682>
	    rotate <0.0000,-67.475,0.0000>
	    translate mol_0_pos_3
	   }
	  }
	 }

#declare mol_0_bond2 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546766,1.0000,1.0000>
	    rotate <0.0000,0.0000,-28.0591>
	    rotate <0.0000,113.5,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546766,1.0000,1.0000>
	    rotate <0.0000,0.0000,151.941>
	    rotate <0.0000,113.5,0.0000>
	    translate mol_0_pos_4
	   }
	  }
	 }

#declare mol_0_bond3 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547472,1.0000,1.0000>
	    rotate <0.0000,0.0000,69.0125>
	    rotate <0.0000,-178.309,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547472,1.0000,1.0000>
	    rotate <0.0000,0.0000,249.012>
	    rotate <0.0000,-178.309,0.0000>
	    translate mol_0_pos_5
	   }
	  }
	 }

#declare mol_0_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547501,1.0000,1.0000>
	    rotate <0.0000,0.0000,-27.1264>
	    rotate <0.0000,-113.3,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547501,1.0000,1.0000>
	    rotate <0.0000,0.0000,152.874>
	    rotate <0.0000,-113.3,0.0000>
	    translate mol_0_pos_6
	   }
	  }
	 }

#declare mol_0_bond5 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547165,1.0000,1.0000>
	    rotate <0.0000,0.0000,27.9828>
	    rotate <0.0000,66.1067,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547165,1.0000,1.0000>
	    rotate <0.0000,0.0000,207.983>
	    rotate <0.0000,66.1067,0.0000>
	    translate mol_0_pos_7
	   }
	  }
	 }

#declare mol_0_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546944,1.0000,1.0000>
	    rotate <0.0000,0.0000,-69.2806>
	    rotate <0.0000,-0.580145,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546944,1.0000,1.0000>
	    rotate <0.0000,0.0000,110.719>
	    rotate <0.0000,-0.580145,0.0000>
	    translate mol_0_pos_8
	   }
	  }
	 }

#declare mol_0_bond7 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.486188,1.0000,1.0000>
	    rotate <0.0000,0.0000,69.5304>
	    rotate <0.0000,176.986,0.0000>
	    translate mol_0_pos_3
	   }
	   object {
	    bond_1
	    pigment{color Color_HO}
	    scale <0.486188,1.0000,1.0000>
	    rotate <0.0000,0.0000,249.53>
	    rotate <0.0000,176.986,0.0000>
	    translate mol_0_pos_9
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule mol_0
#ifdef (TRANS)
#declare mol_0_atoms = merge {
#else
#declare mol_0_atoms = union {
#end //(End of TRANS)
	  object{mol_0_atom1}
	  object{mol_0_atom2}
	  object{mol_0_atom3}
	  object{mol_0_atom4}
	  object{mol_0_atom5}
	  object{mol_0_atom6}
	  object{mol_0_atom7}
	  object{mol_0_atom8}
	  object{mol_0_atom9}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare mol_0_bonds = union {
	  object{mol_0_bond0}
	  object{mol_0_bond1}
	  object{mol_0_bond2}
	  object{mol_0_bond3}
	  object{mol_0_bond4}
	  object{mol_0_bond5}
	  object{mol_0_bond6}
	  object{mol_0_bond7}
	 }
#end


//Definition of molecule mol_0
#if (SPF)
#declare mol_0 = object{
	  mol_0_atoms
#else
#declare mol_0 = union {
	  object{mol_0_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{mol_0_bonds}
	   object{mol_0_atoms}
	  }
#else
	  object{mol_0_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-4.09052,-3.83227>
//	    <5.9635,4.50322,4.21748>
	 }

//Center of molecule mol_0 (bounding box)
#declare mol_0_center = <-1.48175,-0.206353,-0.192603>;

mol_0
