//Povray v3 code generated by Open Babel
//Author: Steffen Reith <streit@streit.cc>
//Update (2010): Noel O'Boyle and Steven Wathen
//Date: Mon Jan 12 18:26:24 CET 2026

//Set some global parameters for display options
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"

// create a regular point light source
light_source {
  <6.40946,4.23825,-7.44078>
  color rgb <1,1,1>    // light's color
}

// set a color of the background (sky)
background { color rgb <0.95 0.95 0.95> }

// perspective (default) camera
camera {
  location  <4.40946,1.23825,-9.44078>
  look_at   <4.40946,1.23825,0.559225>
  right     x*image_width/image_height
}

//Include header for povray
#include "babel_povray3.inc"

//Use PovRay3.6
#version 3.6;

//Print name of molecule while rendering
#render "\b\b \n\n"

//Coodinates of atoms 1 - 21
#declare mol_0_pos_1 = <1.02817,0.968944,-0.268737>;
#declare mol_0_pos_2 = <2.47513,1.18468,-0.596922>;
#declare mol_0_pos_3 = <2.88338,1.54202,-1.6924>;
#declare mol_0_pos_4 = <3.2485,0.925796,0.541569>;
#declare mol_0_pos_5 = <4.65433,1.06948,0.478628>;
#declare mol_0_pos_6 = <5.37317,0.597168,-0.622973>;
#declare mol_0_pos_7 = <6.75898,0.753881,-0.671118>;
#declare mol_0_pos_8 = <7.43248,1.35769,0.388044>;
#declare mol_0_pos_9 = <6.72231,1.79466,1.50787>;
#declare mol_0_pos_10 = <5.32875,1.63876,1.57103>;
#declare mol_0_pos_11 = <4.65699,2.11136,2.80923>;
#declare mol_0_pos_12 = <5.08069,3.03781,3.47856>;
#declare mol_0_pos_13 = <3.589,1.37198,3.17624>;
#declare mol_0_pos_14 = <0.436345,1.05568,-1.18525>;
#declare mol_0_pos_15 = <0.692587,1.72894,0.440344>;
#declare mol_0_pos_16 = <0.880806,-0.0345849,0.137879>;
#declare mol_0_pos_17 = <4.87306,0.120878,-1.46259>;
#declare mol_0_pos_18 = <7.31149,0.411389,-1.5438>;
#declare mol_0_pos_19 = <8.51187,1.4875,0.34346>;
#declare mol_0_pos_20 = <7.26062,2.25544,2.33513>;
#declare mol_0_pos_21 = <3.40011,0.623815,2.57952>;

//Povray-description of atoms 1 - 21
#declare mol_0_atom1 = object {
	  Atom_C
	  translate mol_0_pos_1
	 }
#declare mol_0_atom2 = object {
	  Atom_C
	  translate mol_0_pos_2
	 }
#declare mol_0_atom3 = object {
	  Atom_O
	  translate mol_0_pos_3
	 }
#declare mol_0_atom4 = object {
	  Atom_O
	  translate mol_0_pos_4
	 }
#declare mol_0_atom5 = object {
	  Atom_C
	  translate mol_0_pos_5
	 }
#declare mol_0_atom6 = object {
	  Atom_C
	  translate mol_0_pos_6
	 }
#declare mol_0_atom7 = object {
	  Atom_C
	  translate mol_0_pos_7
	 }
#declare mol_0_atom8 = object {
	  Atom_C
	  translate mol_0_pos_8
	 }
#declare mol_0_atom9 = object {
	  Atom_C
	  translate mol_0_pos_9
	 }
#declare mol_0_atom10 = object {
	  Atom_C
	  translate mol_0_pos_10
	 }
#declare mol_0_atom11 = object {
	  Atom_C
	  translate mol_0_pos_11
	 }
#declare mol_0_atom12 = object {
	  Atom_O
	  translate mol_0_pos_12
	 }
#declare mol_0_atom13 = object {
	  Atom_O
	  translate mol_0_pos_13
	 }
#declare mol_0_atom14 = object {
	  Atom_H
	  translate mol_0_pos_14
	 }
#declare mol_0_atom15 = object {
	  Atom_H
	  translate mol_0_pos_15
	 }
#declare mol_0_atom16 = object {
	  Atom_H
	  translate mol_0_pos_16
	 }
#declare mol_0_atom17 = object {
	  Atom_H
	  translate mol_0_pos_17
	 }
#declare mol_0_atom18 = object {
	  Atom_H
	  translate mol_0_pos_18
	 }
#declare mol_0_atom19 = object {
	  Atom_H
	  translate mol_0_pos_19
	 }
#declare mol_0_atom20 = object {
	  Atom_H
	  translate mol_0_pos_20
	 }
#declare mol_0_atom21 = object {
	  Atom_H
	  translate mol_0_pos_21
	 }

//Povray-description of bonds 1 - 21
#if (BAS)
#declare mol_0_bond0 = object {
	  bond_1
	  scale <1.49932,1.0000,1.0000>
	  rotate <0.0000,0.0000,8.27304>
	  rotate <0.0000,12.779,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond1 = object {
	  bond_2
	  scale <1.22247,1.0000,1.0000>
	  rotate <0.0000,0.0000,16.9962>
	  rotate <0.0000,69.5614,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond2 = object {
	  bond_1
	  scale <1.40046,1.0000,1.0000>
	  rotate <0.0000,0.0000,-10.6528>
	  rotate <0.0000,-55.8119,0.0000>
	  translate mol_0_pos_2
	 }
#declare mol_0_bond3 = object {
	  bond_1
	  scale <1.41456,1.0000,1.0000>
	  rotate <0.0000,0.0000,5.82994>
	  rotate <0.0000,2.5635,0.0000>
	  translate mol_0_pos_4
	 }
#declare mol_0_bond4 = object {
	  bond_1
	  scale <1.39761,1.0000,1.0000>
	  rotate <0.0000,0.0000,-19.7516>
	  rotate <0.0000,56.8741,0.0000>
	  translate mol_0_pos_5
	 }
#declare mol_0_bond5 = object {
	  bond_2
	  scale <1.39548,1.0000,1.0000>
	  rotate <0.0000,0.0000,6.44797>
	  rotate <0.0000,1.98976,0.0000>
	  translate mol_0_pos_6
	 }
#declare mol_0_bond6 = object {
	  bond_1
	  scale <1.39285,1.0000,1.0000>
	  rotate <0.0000,0.0000,25.6905>
	  rotate <0.0000,-57.5483,0.0000>
	  translate mol_0_pos_7
	 }
#declare mol_0_bond7 = object {
	  bond_2
	  scale <1.39617,1.0000,1.0000>
	  rotate <0.0000,0.0000,18.2387>
	  rotate <0.0000,-122.382,0.0000>
	  translate mol_0_pos_8
	 }
#declare mol_0_bond8 = object {
	  bond_1
	  scale <1.40367,1.0000,1.0000>
	  rotate <0.0000,0.0000,-6.37682>
	  rotate <0.0000,-177.405,0.0000>
	  translate mol_0_pos_9
	 }
#declare mol_0_bond9 = object {
	  bond_2
	  scale <1.40438,1.0000,1.0000>
	  rotate <0.0000,0.0000,23.9138>
	  rotate <0.0000,-58.3098,0.0000>
	  translate mol_0_pos_5
	 }
#declare mol_0_bond10 = object {
	  bond_1
	  scale <1.48585,1.0000,1.0000>
	  rotate <0.0000,0.0000,18.5459>
	  rotate <0.0000,-118.481,0.0000>
	  translate mol_0_pos_10
	 }
#declare mol_0_bond11 = object {
	  bond_2
	  scale <1.21895,1.0000,1.0000>
	  rotate <0.0000,0.0000,49.4681>
	  rotate <0.0000,-57.6657,0.0000>
	  translate mol_0_pos_11
	 }
#declare mol_0_bond12 = object {
	  bond_1
	  scale <1.34981,1.0000,1.0000>
	  rotate <0.0000,0.0000,-33.2138>
	  rotate <0.0000,-161.035,0.0000>
	  translate mol_0_pos_11
	 }
#declare mol_0_bond13 = object {
	  bond_1
	  scale <1.09442,1.0000,1.0000>
	  rotate <0.0000,0.0000,4.54565>
	  rotate <0.0000,122.852,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond14 = object {
	  bond_1
	  scale <1.09225,1.0000,1.0000>
	  rotate <0.0000,0.0000,44.0919>
	  rotate <0.0000,-115.326,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond15 = object {
	  bond_1
	  scale <1.09276,1.0000,1.0000>
	  rotate <0.0000,0.0000,-66.6852>
	  rotate <0.0000,-109.921,0.0000>
	  translate mol_0_pos_1
	 }
#declare mol_0_bond16 = object {
	  bond_1
	  scale <1.08716,1.0000,1.0000>
	  rotate <0.0000,0.0000,-25.9831>
	  rotate <0.0000,120.779,0.0000>
	  translate mol_0_pos_6
	 }
#declare mol_0_bond17 = object {
	  bond_1
	  scale <1.08818,1.0000,1.0000>
	  rotate <0.0000,0.0000,-18.3451>
	  rotate <0.0000,57.6615,0.0000>
	  translate mol_0_pos_7
	 }
#declare mol_0_bond18 = object {
	  bond_1
	  scale <1.08807,1.0000,1.0000>
	  rotate <0.0000,0.0000,6.85165>
	  rotate <0.0000,2.36529,0.0000>
	  translate mol_0_pos_8
	 }
#declare mol_0_bond19 = object {
	  bond_1
	  scale <1.08924,1.0000,1.0000>
	  rotate <0.0000,0.0000,25.0258>
	  rotate <0.0000,-56.9477,0.0000>
	  translate mol_0_pos_9
	 }
#declare mol_0_bond20 = object {
	  bond_1
	  scale <0.975454,1.0000,1.0000>
	  rotate <0.0000,0.0000,-50.0842>
	  rotate <0.0000,107.565,0.0000>
	  translate mol_0_pos_13
	 }
#end //(BAS-Bonds)

#if (CST)
#declare mol_0_bond0 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.749658,1.0000,1.0000>
	    rotate <0.0000,0.0000,8.27304>
	    rotate <0.0000,12.779,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.749658,1.0000,1.0000>
	    rotate <0.0000,0.0000,188.273>
	    rotate <0.0000,12.779,0.0000>
	    translate mol_0_pos_2
	   }
	  }
	 }

#declare mol_0_bond1 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_C2}
	    scale <0.611235,1.0000,1.0000>
	    rotate <0.0000,0.0000,16.9962>
	    rotate <0.0000,69.5614,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.611235,1.0000,1.0000>
	    rotate <0.0000,0.0000,196.996>
	    rotate <0.0000,69.5614,0.0000>
	    translate mol_0_pos_3
	   }
	  }
	 }

#declare mol_0_bond2 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.70023,1.0000,1.0000>
	    rotate <0.0000,0.0000,-10.6528>
	    rotate <0.0000,-55.8119,0.0000>
	    translate mol_0_pos_2
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.70023,1.0000,1.0000>
	    rotate <0.0000,0.0000,169.347>
	    rotate <0.0000,-55.8119,0.0000>
	    translate mol_0_pos_4
	   }
	  }
	 }

#declare mol_0_bond3 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.707278,1.0000,1.0000>
	    rotate <0.0000,0.0000,5.82994>
	    rotate <0.0000,2.5635,0.0000>
	    translate mol_0_pos_4
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.707278,1.0000,1.0000>
	    rotate <0.0000,0.0000,185.83>
	    rotate <0.0000,2.5635,0.0000>
	    translate mol_0_pos_5
	   }
	  }
	 }

#declare mol_0_bond4 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.698807,1.0000,1.0000>
	    rotate <0.0000,0.0000,-19.7516>
	    rotate <0.0000,56.8741,0.0000>
	    translate mol_0_pos_5
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.698807,1.0000,1.0000>
	    rotate <0.0000,0.0000,160.248>
	    rotate <0.0000,56.8741,0.0000>
	    translate mol_0_pos_6
	   }
	  }
	 }

#declare mol_0_bond5 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.697739,1.0000,1.0000>
	    rotate <0.0000,0.0000,6.44797>
	    rotate <0.0000,1.98976,0.0000>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.697739,1.0000,1.0000>
	    rotate <0.0000,0.0000,186.448>
	    rotate <0.0000,1.98976,0.0000>
	    translate mol_0_pos_7
	   }
	  }
	 }

#declare mol_0_bond6 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.696424,1.0000,1.0000>
	    rotate <0.0000,0.0000,25.6905>
	    rotate <0.0000,-57.5483,0.0000>
	    translate mol_0_pos_7
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.696424,1.0000,1.0000>
	    rotate <0.0000,0.0000,205.69>
	    rotate <0.0000,-57.5483,0.0000>
	    translate mol_0_pos_8
	   }
	  }
	 }

#declare mol_0_bond7 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.698087,1.0000,1.0000>
	    rotate <0.0000,0.0000,18.2387>
	    rotate <0.0000,-122.382,0.0000>
	    translate mol_0_pos_8
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.698087,1.0000,1.0000>
	    rotate <0.0000,0.0000,198.239>
	    rotate <0.0000,-122.382,0.0000>
	    translate mol_0_pos_9
	   }
	  }
	 }

#declare mol_0_bond8 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.701836,1.0000,1.0000>
	    rotate <0.0000,0.0000,-6.37682>
	    rotate <0.0000,-177.405,0.0000>
	    translate mol_0_pos_9
	   }
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.701836,1.0000,1.0000>
	    rotate <0.0000,0.0000,173.623>
	    rotate <0.0000,-177.405,0.0000>
	    translate mol_0_pos_10
	   }
	  }
	 }

#declare mol_0_bond9 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.702189,1.0000,1.0000>
	    rotate <0.0000,0.0000,23.9138>
	    rotate <0.0000,-58.3098,0.0000>
	    translate mol_0_pos_5
	   }
	   object {
	    bond_2
	    pigment{color Color_Car}
	    scale <0.702189,1.0000,1.0000>
	    rotate <0.0000,0.0000,203.914>
	    rotate <0.0000,-58.3098,0.0000>
	    translate mol_0_pos_10
	   }
	  }
	 }

#declare mol_0_bond10 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.742923,1.0000,1.0000>
	    rotate <0.0000,0.0000,18.5459>
	    rotate <0.0000,-118.481,0.0000>
	    translate mol_0_pos_10
	   }
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.742923,1.0000,1.0000>
	    rotate <0.0000,0.0000,198.546>
	    rotate <0.0000,-118.481,0.0000>
	    translate mol_0_pos_11
	   }
	  }
	 }

#declare mol_0_bond11 = object {
	  union {
	   object {
	    bond_2
	    pigment{color Color_C2}
	    scale <0.609475,1.0000,1.0000>
	    rotate <0.0000,0.0000,49.4681>
	    rotate <0.0000,-57.6657,0.0000>
	    translate mol_0_pos_11
	   }
	   object {
	    bond_2
	    pigment{color Color_O2}
	    scale <0.609475,1.0000,1.0000>
	    rotate <0.0000,0.0000,229.468>
	    rotate <0.0000,-57.6657,0.0000>
	    translate mol_0_pos_12
	   }
	  }
	 }

#declare mol_0_bond12 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C2}
	    scale <0.674905,1.0000,1.0000>
	    rotate <0.0000,0.0000,-33.2138>
	    rotate <0.0000,-161.035,0.0000>
	    translate mol_0_pos_11
	   }
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.674905,1.0000,1.0000>
	    rotate <0.0000,0.0000,146.786>
	    rotate <0.0000,-161.035,0.0000>
	    translate mol_0_pos_13
	   }
	  }
	 }

#declare mol_0_bond13 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.547212,1.0000,1.0000>
	    rotate <0.0000,0.0000,4.54565>
	    rotate <0.0000,122.852,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.547212,1.0000,1.0000>
	    rotate <0.0000,0.0000,184.546>
	    rotate <0.0000,122.852,0.0000>
	    translate mol_0_pos_14
	   }
	  }
	 }

#declare mol_0_bond14 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546124,1.0000,1.0000>
	    rotate <0.0000,0.0000,44.0919>
	    rotate <0.0000,-115.326,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546124,1.0000,1.0000>
	    rotate <0.0000,0.0000,224.092>
	    rotate <0.0000,-115.326,0.0000>
	    translate mol_0_pos_15
	   }
	  }
	 }

#declare mol_0_bond15 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_C3}
	    scale <0.546379,1.0000,1.0000>
	    rotate <0.0000,0.0000,-66.6852>
	    rotate <0.0000,-109.921,0.0000>
	    translate mol_0_pos_1
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.546379,1.0000,1.0000>
	    rotate <0.0000,0.0000,113.315>
	    rotate <0.0000,-109.921,0.0000>
	    translate mol_0_pos_16
	   }
	  }
	 }

#declare mol_0_bond16 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.543579,1.0000,1.0000>
	    rotate <0.0000,0.0000,-25.9831>
	    rotate <0.0000,120.779,0.0000>
	    translate mol_0_pos_6
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.543579,1.0000,1.0000>
	    rotate <0.0000,0.0000,154.017>
	    rotate <0.0000,120.779,0.0000>
	    translate mol_0_pos_17
	   }
	  }
	 }

#declare mol_0_bond17 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.544089,1.0000,1.0000>
	    rotate <0.0000,0.0000,-18.3451>
	    rotate <0.0000,57.6615,0.0000>
	    translate mol_0_pos_7
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.544089,1.0000,1.0000>
	    rotate <0.0000,0.0000,161.655>
	    rotate <0.0000,57.6615,0.0000>
	    translate mol_0_pos_18
	   }
	  }
	 }

#declare mol_0_bond18 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.544036,1.0000,1.0000>
	    rotate <0.0000,0.0000,6.85165>
	    rotate <0.0000,2.36529,0.0000>
	    translate mol_0_pos_8
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.544036,1.0000,1.0000>
	    rotate <0.0000,0.0000,186.852>
	    rotate <0.0000,2.36529,0.0000>
	    translate mol_0_pos_19
	   }
	  }
	 }

#declare mol_0_bond19 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_Car}
	    scale <0.544622,1.0000,1.0000>
	    rotate <0.0000,0.0000,25.0258>
	    rotate <0.0000,-56.9477,0.0000>
	    translate mol_0_pos_9
	   }
	   object {
	    bond_1
	    pigment{color Color_H}
	    scale <0.544622,1.0000,1.0000>
	    rotate <0.0000,0.0000,205.026>
	    rotate <0.0000,-56.9477,0.0000>
	    translate mol_0_pos_20
	   }
	  }
	 }

#declare mol_0_bond20 = object {
	  union {
	   object {
	    bond_1
	    pigment{color Color_O3}
	    scale <0.487727,1.0000,1.0000>
	    rotate <0.0000,0.0000,-50.0842>
	    rotate <0.0000,107.565,0.0000>
	    translate mol_0_pos_13
	   }
	   object {
	    bond_1
	    pigment{color Color_HO}
	    scale <0.487727,1.0000,1.0000>
	    rotate <0.0000,0.0000,129.916>
	    rotate <0.0000,107.565,0.0000>
	    translate mol_0_pos_21
	   }
	  }
	 }

#end // (CST-Bonds)


//All atoms of molecule mol_0
#ifdef (TRANS)
#declare mol_0_atoms = merge {
#else
#declare mol_0_atoms = union {
#end //(End of TRANS)
	  object{mol_0_atom1}
	  object{mol_0_atom2}
	  object{mol_0_atom3}
	  object{mol_0_atom4}
	  object{mol_0_atom5}
	  object{mol_0_atom6}
	  object{mol_0_atom7}
	  object{mol_0_atom8}
	  object{mol_0_atom9}
	  object{mol_0_atom10}
	  object{mol_0_atom11}
	  object{mol_0_atom12}
	  object{mol_0_atom13}
	  object{mol_0_atom14}
	  object{mol_0_atom15}
	  object{mol_0_atom16}
	  object{mol_0_atom17}
	  object{mol_0_atom18}
	  object{mol_0_atom19}
	  object{mol_0_atom20}
	  object{mol_0_atom21}
	 }

//Bonds only needed for ball and sticks or capped sticks models
#if (BAS | CST)
#declare mol_0_bonds = union {
	  object{mol_0_bond0}
	  object{mol_0_bond1}
	  object{mol_0_bond2}
	  object{mol_0_bond3}
	  object{mol_0_bond4}
	  object{mol_0_bond5}
	  object{mol_0_bond6}
	  object{mol_0_bond7}
	  object{mol_0_bond8}
	  object{mol_0_bond9}
	  object{mol_0_bond10}
	  object{mol_0_bond11}
	  object{mol_0_bond12}
	  object{mol_0_bond13}
	  object{mol_0_bond14}
	  object{mol_0_bond15}
	  object{mol_0_bond16}
	  object{mol_0_bond17}
	  object{mol_0_bond18}
	  object{mol_0_bond19}
	  object{mol_0_bond20}
	 }
#end


//Definition of molecule mol_0
#if (SPF)
#declare mol_0 = object{
	  mol_0_atoms
#else
#declare mol_0 = union {
	  object{mol_0_atoms}
#if (BAS | CST)//(Not really needed at moment!)
#if (TRANS)
	  difference {
	   object{mol_0_bonds}
	   object{mol_0_atoms}
	  }
#else
	  object{mol_0_bonds}
#end //(End of TRANS)
#end //(End of (BAS|CST))
#end //(End of SPF)
//	  bounded_by {
//	   box {
//	    <-3,-3.03458,-4.6924>
//	    <11.5119,6.03781,6.47856>
	 }

//Center of molecule mol_0 (bounding box)
#declare mol_0_center = <-4.25593,-1.50161,-0.893077>;

mol_0
